### ISSUE TITLE
[How-To] How to set-up on Synology NAS?

### ISSUE THREAD

**Issue by ks2018ks** [origamiofficial/docker-ngrok-plex#3] opened 2023-01-23 16:40 UTC
Hi Any idea how I can set this up on a Synology NAS?

I'm trying to start with your helpful command template.  I want to install it in a subdirectory of /volume1/docker/, but 
1. not sure what should go after the colon in the modified version below:
2. not sure if I have specified the plex base url correctly: in my case the docker installation is on NAS 192.168.1.12 but the plex server is on NAS 192.168.1.15.

```
docker run -d \
  --name=ngrok-plex \
  -e TZ=Europe/London 
  -e PLEX_BaseURL='http://192.168.1.15:32400' `my plex server is on a different NAS than the one I run docker on` \
  -e PLEX_Token='myplextoken' 
  -e NGROK_Token='myngroktoken' 
-v /volume1/docker/ngrok-plex: `<---do I need to put something after the colon, here?` \
  rlabinc/ngrok-plex:latest 
```

Not sure what to do next?

After running the command, I don't get an error, but there's nothing in my /volume1/docker/ngrok-plex directory and the docker log for the container shows:

```
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
tWaiting 5 seconds for ngrok to start up
Traceback (most recent call last):
File "/root/./ngrok-plex.py", line 41, in <module>
ngrokurlclean= ngrokurl.split('//')[-1]
                   ^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'split'
```			

As you can tell, I'm not a linux native(!), but would appreciate any help you can give

**Comment by origamiofficial** [comment] 2023-01-25 16:06
Hi @ks2018ks 
It seems like this is a duplicate of issue #1, go check it out. The container has been verified to work fine on all platforms, I am considering this issue as solved. Feel free to reopen if you need further assistance.

**Comment by ks2018ks** [comment] 2023-01-25 17:05
Hi @origamiofficial, I don't think its a duplicate.  I'm not running Plex in Docker.  I have it installed via the Synology Package Manager.  I'm trying to find out how to install your work and configure it onto my Synology NAS, and so far don't understand after running the command where it's been installed, what the error means, or what to do next - e.g. I assume I need to find somewhere a log showing the output of an ngrok command that your work generates to add as external IP address to Plex Server "Custom server access URL", but where will I find it? (I can't work out where your work installs ngrok or configuration files, and I don't know how to specify a folder/directory for the installation, which is why I asked the question in the first post, above.

**Comment by origamiofficial** [comment] 2023-01-25 17:52
@ks2018ks  I'm sorry at first I haven't understood your question. The first thing is it doesn't matter whether you have got a dockerized version of PMS or package installation, all it needed was the correct IP where it can reach and talk with the PMS. The second thing is, I can see you're trying to mount "/volume1/docker/ngrok-plex" but this container doesn't need anything to mount. It doesn't have anything at all to save inside the system. And the third thing is the error you're facing is typically caused by the old image of this project. All you can do now is remove the deployed docker container and deploy a fresh one. To stop the container & remove it use the below command:
```bash
docker stop $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rm -f $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rmi rlabinc/ngrok-plex:latest
```
This command will first stop any running containers that were created from the "rlabinc/ngrok-plex:latest" image, then it will remove the stopped containers and associated files, and finally, it will remove the "rlabinc/ngrok-plex:latest" image itself. Now try to run the container to download the latest version from the docker hub. To run the container deploy the container again use the below command:
```bash
docker run -d --network host \
  --name=ngrok-plex \
  -e TZ=Europe/London `#optional` \
  -e PLEX_BaseURL='http://192.168.1.15:32400' `Your Plex server (NAS) IP` \
  -e PLEX_Token='YoUr-PlEx-T0kEn' `#better to use single quotes` \
  -e NGROK_Token='y0UrNgR0k_T0kEn' `#better to use single quotes` \
  rlabinc/ngrok-plex:latest
  ```
Do not put anything besides these items. After login into the [ngrok website](https://dashboard.ngrok.com/login) go to [THIS](https://dashboard.ngrok.com/get-started/your-authtoken) page to get your ngrok token and put it inside single quotes of `NGROK_Token` environment variables. To get the plex token to follow [THIS](https://github.com/origamiofficial/docker-ngrok-plex#extracting-the-plex-token) guide and put it inside single quotes of `PLEX_Token` environment variables. If you can access your PMS through this `http://192.168.1.15:32400` from the browser then the variable for `PLEX_BaseURL` is correct.
To access or get the logs for this container use the below command unless you've changed the name of the container:
```bash
docker logs ngrok-plex
```
To get the list of all containers in your system use the below command:
```bash
docker ps -a
```
If you need any more help, feel free to ask here.

**Comment by origamiofficial** [comment] 2023-01-25 17:58
Please note, I've never used any Synology NAS or never had one. All of the information is provided based on Linux.

**Comment by ks2018ks** [comment] 2023-01-27 10:15
Thanks for taking the time to try to explain.

When I entered the first command, 
`docker stop $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rm -f $(docker ps -a -q --filter ancestor=rlabinc/ngrok-plex:latest) && docker rmi rlabinc/ngrok-plex:latest`

I get
`"docker stop" requires at least 1 argument.
See 'docker stop --help'.`

When I enter the second command (with the correct token for plex and ngrok I get a 64-character string.

The log looks like this:
`docker logs ngrok-plex
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
Waiting 5 seconds for ngrok to start up
ngrok base url = 0.tcp.eu.ngrok.io
ngrok url and ip no port = 18.158.249.75
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPConnection object at 0x7f9c79ee2bd0>, 'Connection to 192.156.1.5 timed out. (connect timeout=30)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.156.1.5', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9c79ee2bd0>, 'Connection to 192.156.1.5 timed out. (connect timeout=30)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/./ngrok-plex.py", line 69, in <module>
    plex = PlexServer(PLEX_BaseURL, PLEX_Token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 553, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPConnectionPool(host='192.156.1.5', port=32400): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9c79ee2bd0>, 'Connection to 192.156.1.5 timed out. (connect timeout=30)'))`

I assume I still need to find what ngrok has generated to add as an external IP address and then enter that in my Plex Server "Custom server access URL".  Is that right?

**Comment by origamiofficial** [comment] 2023-01-27 18:44
@ks2018ks There is no need to manually enter anything on the Plex dashboard. The container will handle everything for you. It seems like it can't reach your PMS over the IP `192.168.1.15`. Something is wrong on your end. Can you ping PMS IP from the Nas where you're trying to deploy the container? Also, there is no need to remove the IP & Port of Ngrok because it randomly changes every 2 hours. It'll help me to read the log more preciously.

**Comment by ks2018ks** [comment] 2023-01-29 14:16
To try to make things simpler I decided to try to install it on the same NAS as the NAS running plex.  In that case should I used 127.0.0.1.  This time the log is as follows:

```
docker logs ngrok-plex
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
Waiting 5 seconds for ngrok to start up
ngrok base url = 2.tcp.eu.ngrok.io
ngrok url and ip no port = 18.156.13.209
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f42e6c330d0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f42e6c330d0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/./ngrok-plex.py", line 69, in <module>
    plex = PlexServer(PLEX_BaseURL, PLEX_Token)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 115, in __init__
    data = self.query(self.key, timeout=self._timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/plexapi/server.py", line 745, in query
    response = method(url, headers=headers, timeout=timeout, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 565, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=32400): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f42e6c330d0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

**Comment by origamiofficial** [comment] 2023-01-31 11:58
`127.0.0.1`, also known as localhost, refers to the loopback IP address of the host machine. When you access `127.0.0.1` from inside a container, it refers to the loopback address of the container, not the host machine. To access the host machine from inside a container, you need to use the host's IP address. Why don't you use your Plex NAS IP? Make sure the NAS has a static IP / Address Reservation.

**Comment by ks2018ks** [comment] 2023-01-31 19:12
Thanks for your patience.  It didn't occur to me that a docker container on a NAS would have a different IP address as the NAS!

Nonetheless, when I use the NAS IP address (which Plex and Docker are both running on), I get a connection error & timeout (as below).  Any ideas how to overcome that?

```
docker logs ngrok-plex
Authtoken saved to configuration file: /root/.config/ngrok/ngrok.yml
Waiting 5 seconds for ngrok to start up
ngrok base url = 6.tcp.eu.ngrok.io
ngrok url and ip no port = 52.28.247.255
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
TimeoutError: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.11/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connection.py", line 179, in _new_conn



```

**Comment by origamiofficial** [comment] 2023-02-01 04:46
A Docker container running on a NAS (Network Attached Storage) device is isolated from the host system, including its network stack. The container has its own network interface with a unique IP address assigned by the Docker daemon on the host. The host and the container communicate through a virtual network, which provides network address translation (NAT) between the host and the container. This allows the container to access the network as if it were a separate host with its own IP address, while also allowing the host to communicate with the container.
You need to put the NAS IP from which you can access the Plex Web UI from your mobile or laptop. Below is the link format:
`http://[IP]/web/index.html`
If you can access it then use the same IP on environment variable too. It'll work flawlessly.

**Comment by ks2018ks** [comment] 2023-02-01 14:08
Thanks for the explanation.  

The IP address and port supplied as the `PLEX_BaseURL`  does indeed launch the Plex UI when entered in a browser.  

What else could be causing those errors?

**Comment by origamiofficial** [comment] 2023-02-01 14:20
Have you correctly extract the Plex Token ?

**Comment by origamiofficial** [comment] 2023-02-01 14:32
The token has exactly no static format so can't confirm whether it starts with `x_` or not. But you can check yourself by visiting the below link in your browser incognito mode. If it shows your users list then you've got the correct token.
Link format: `https://plex.tv/api/users/?X-Plex-Token=XXXXX`
Note: You ONLY need to replace XXXXX with your actual token.

**Comment by ks2018ks** [comment] 2023-02-01 14:40
Yes that works.  It appears the token is correct.

**Comment by origamiofficial** [comment] 2023-02-01 14:50
You've entered everything correctly but still facing `TimeoutError: timed out`, this is weird. You can do another thing, first remove the container & pull the latest image from Dockerhub by running:
```bash
docker pull rlabinc/ngrok-plex:latest
```
and then run again by:
```bash
docker run -d --network host \
  --name=ngrok-plex \
  -e TZ=Europe/London `#optional` \
  -e PLEX_Token='XXXXXXXXXX' `#better to use single quotes` \
  -e NGROK_Token='XXXXXXXXXX' `#better to use single quotes` \
  rlabinc/ngrok-plex:latest
```
Note: I've just removed the `PLEX_BaseURL`.
Let me know what happened.

**Comment by ks2018ks** [comment] 2023-02-01 15:17
I was doing that just now, but still get the same `TimeoutError: timed out` .  

Just wondering if it's something to do with certificates.  When I first log in to Plex via a browser,  The browser shows something like a SSL certificate :

`This server could not prove that it is <NAS/Plex ip address>; its security certificate is from *.e0f91d7887764eae8405a8af27df9025.plex.direct
`

Then I have to click advanced and proceed

**Comment by origamiofficial** [comment] 2023-02-01 15:56
Go to `Plex Web UI > Settings > Network > SHOW ADVANCED` then change below settings:
`Secure connections` to `Preferred`
&
Disable `Strict TLS configuration`

Then remove container & recreate with:
```bash
docker run -d --network host \
  --name=ngrok-plex \
  -e TZ=Europe/London `#optional` \
  -e PLEX_BaseURL='http://IP:32400' `#Your Plex server (NAS) IP` \
  -e PLEX_Token='YoUr-PlEx-T0kEn' `#better to use single quotes` \
  -e NGROK_Token='y0UrNgR0k_T0kEn' `#better to use single quotes` \
  rlabinc/ngrok-plex:latest
```
Let me know if this time worked or not.

**Comment by ks2018ks** [comment] 2023-02-01 16:00
OK:
These were already set that way - i.e.

`Secure connections` was already set to `Preferred`
`Strict TLS configuration` already unticked

**Comment by origamiofficial** [comment] 2023-02-01 16:03
Can you share your full command here with replace the tokens with `XXXXX` ?

**Comment by ks2018ks** [comment] 2023-02-01 16:07
The command is:
```
docker run -d --network host \
  --name=ngrok-plex \
  -e TZ=Europe/London `#optional` \
  -e PLEX_BaseURL='http://192.168.1.5:32400' `#Your Plex server (NAS) IP` \
  -e PLEX_Token='XXXXX' `#better to use single quotes` \
  -e NGROK_Token='XXXXX' `#better to use single quotes` \
  rlabinc/ngrok-plex:latest
```

**Comment by origamiofficial** [comment] 2023-02-01 16:14
Try this one, I've just removed the comments and added the Plex generated secure domain.
```bash
docker run -d --network host \
  --name=ngrok-plex \
  -e TZ=Europe/London \
  -e PLEX_BaseURL='https://192-168-1-5.e0f91d7887764eae8405a8af27df9025.plex.direct:32400' \
  -e PLEX_Token='XXXXX' \
  -e NGROK_Token='XXXXX' \
  rlabinc/ngrok-plex:latest
  ```
  Also, change the TimeZone according to your location.

**Comment by origamiofficial** [comment] 2023-02-01 16:15
Go ahead and test this.

**Comment by ks2018ks** [comment] 2023-02-01 16:20
Thank you!  That seems to have done the trick.  (I was just able to connect to Plex on a mobile phone over 4G).

Is this part stable?: `https://192-168-1-5.e0f91d7887764eae8405a8af27df9025.plex.direct:32400 `.  Or will it change if I have to log in with my plex account again?

**Comment by origamiofficial** [comment] 2023-02-01 16:50
Here's the breakdown,
| Item | Meaning | Changeable |
| :----: | :----: | :----: |
| `https://` | Secure version of HTTP | No |
| `192-168-1-5` | PMS IP [Replaced `.` with `-`] | Yes/No |
| `e0f91d7887764eae8405a8af27df9025` | Your PMS CertificateUUID | No |
| `plex.direct` | Plex domain | No |
| `32400` | PMS port | No |

The PMS IP part depends on whether you have a static local IP (some router ex: Tp-Link called it "Address Reservation) for Plex NAS or not. It depends on your setup.
The PMS CertificateUUID won't change unless you've completely reinstalled your Plex setup.

**Comment by origamiofficial** [comment] 2023-02-01 17:08
As @ks2018ks's problem solved and the container has been verified to work fine, I am considering this issue as solved. Feel free to reopen if you need further assistance.

**Closed by origamiofficial** 2023-02-01 17:08 UTC
Labels: good first issue

**Comment by ks2018ks** [comment] 2023-02-01 18:31
Thanks for the explanation. The NAS IP is fixed, so from your explanation, it should all start that way. Is it ok that my survive PMS CertificateUUID is published here?

**Comment by origamiofficial** [comment] 2023-02-02 02:21
Shouldn't be a problem because the CertificateUUID/HASH is - I guess - a hash of the user or server name/id.

**Comment by ks2018ks** [comment] 2023-02-02 08:22
Removed it from my posts just in case, would you mind doing the same?

**Comment by origamiofficial** [comment] 2023-02-02 08:48
Done!

**Comment by toyanucci** [comment] 2023-02-04 15:04
Late to the party but having the same problem.  Can you direct me where to my CertificateUUID/HASH?

And thanks for making all of this so easy to setup!
